language: java
jdk:
  - oraclejdk8
services:
  - mysql
before_install:
  - pip install --user codecov
  - mysql -e "create database IF NOT EXISTS attribute_mapper; grant all on attribute_mapper.* to 'root';" -uroot
after_success:
  - codecov

